### ISSUE TITLE
i18n dependency update needed

### ISSUE THREAD

**Issue by rubyconvict** [semaperepelitsa/subdomain_locale#5]
In Gemfile:
    rails (= 4.2.1) ruby depends on
      activejob (= 4.2.1) ruby depends on
        activesupport (= 4.2.1) ruby depends on
          i18n (~> 0.7) ruby

    subdomain_locale (>= 0) ruby depends on
      i18n (~> 0.6.9) ruby

**Comment by semaperepelitsa** [comment]
I've just released an update: 1.2.0. Your issue should now be fixed.

**Comment by rubyconvict** [comment]
Ok, thanks.
