### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by andreiglingeanu** [semaperepelitsa/subdomain_locale#9]
I see that this gem doesn't support rails 5. What stops it from doing so? Is there any way I can help you getting past that?

Thank you for considering that!

**Comment by semaperepelitsa** [comment]
I'm looking into this soon as we are now migrating to Rails 5!

**Comment by andreiglingeanu** [comment]
Awesome. Please let me know if you need any help!

**Comment by semaperepelitsa** [comment]
Released 1.3.0. It looks good to go with a minor change. Please, report any issues.

**Comment by andreiglingeanu** [comment]
Looks fine to me. I'll open up new issues in case I'll find edge cases that will concern those changes. Thank you!
